language: python
python:
  - "3.6"
install: pip install -e .[test]
script:
  # Pylint thinks typing.NamedTuple isn't callable, so disable that check for now
  - pylint src -d fixme,not-callable
  - mypy src --ignore-missing-imports
  - sphinx-build -qW . _build/html
  - sh demo.sh
notifications:
  email: false