language: python
python:
  - "3.5"
install:
  - pip install hypothesis
  - pip install pylint
  - pip install sphinx
script:
  - pylint src -d fixme
  - nosetests --all-modules
  - sphinx-build -qW . _build/html
  - sh demo.sh
notifications:
  email: false